name: custom actions
on:
  workflow_dispatch:
 
jobs:
  clone:
    name: Clone Repository
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: clone data from github
        uses: DaggupatiPavan/new-action2@v2
        with:
          command: 'git clone https://github.com/DaggupatiPavan/java-web-app-docker.git '
          step-name: clone
 
      - name: Upload clone logs and workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: .
 
  build:
    name: Build Project
    runs-on: self-hosted
    needs: clone
    steps:
      - name: Download workspace from artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace
          path: .
 
      - name: build maven package
        uses: DaggupatiPavan/new-action2@v2
        with:
          command: 'mvn clean package'
          step-name: 'maven package'
 
      - name: Upload build logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: .
     
  image-build:
    name: Build Docker Image
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download workspace from artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace
          path: .
 
      - name: Run System Health Check
        uses: DaggupatiPavan/new-action2@v2
        with:
          command: 'docker build -t pavan176/webapp:v.0.1 .'
          step-name: 'docker image build'
 
      - name: Upload Docker build logs
        uses: actions/upload-artifact@v3
        with:
          name: docker-build-logs
          path: .
 
  run-image:
    name: Run Docker Image
    runs-on: self-hosted
    needs: image-build
    steps:
 
      - name: Run System Health Check
        uses: DaggupatiPavan/new-action2@v2
        with:
          command: 'sudo docker run -itd pavan176/webapp:v.0.1'
          step-name: 'container run'
  nginx-image:
    name: nginx
    runs-on: self-hosted
    needs: image-build
    steps:
 
      - name: nginx
        uses: DaggupatiPavan/new-action2@v2
        with:
          command: 'sudo docker run -itd -p 80:80 nginx'
          step-name: 'nginx run'
