name: Custom Actions Workflow
on:
  workflow_dispatch:

jobs:
  clone:
    name: Clone Repository
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Clone data from GitHub
        uses: DaggupatiPavan/new-action2@v3
        with:
          command: 'git clone https://github.com/DaggupatiPavan/java-web-app-docker.git'
          step-name: 'clone'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1 
      - name: Upload clone logs and workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: .

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace
          path: .
 
      - name: Build Maven Package
        uses: DaggupatiPavan/new-action2@v3
        with:
          command: 'mvn clean package'
          step-name: 'maven-package'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-bucket: ${{ secrets.S3_LOGGING_BUCKET }}
          s3-path-prefix: 'github-actions/build-logs/'
      - name: Upload clone logs and workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: .
  image-build:
    name: Build Docker Image
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace
          path: .
 
      - name: Build Docker Image
        uses: DaggupatiPavan/new-action2@v3
        with:
          command: 'docker build -t pavan176/webapp:v.0.1 .'
          step-name: 'docker-image-build'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-bucket: ${{ secrets.S3_LOGGING_BUCKET }}
          s3-path-prefix: 'github-actions/docker-build-logs/'
      - name: Upload clone logs and workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: .
 
  run-image:
    name: Run Docker Image
    runs-on: self-hosted
    needs: image-build
    steps:
      - name: Run Docker Container
        uses: DaggupatiPavan/new-action2@v3
        with:
          command: 'sudo docker run -itd pavan176/webapp:v.0.1'
          step-name: 'container-run'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-bucket: ${{ secrets.S3_LOGGING_BUCKET }}
          s3-path-prefix: 'github-actions/container-run-logs/'
  
  nginx-image:
    name: Nginx
    runs-on: self-hosted
    needs: image-build
    steps:
      - name: Run Nginx Container
        uses: DaggupatiPavan/new-action2@v3
        with:
          command: 'sudo docker run -itd -p 80:80 nginx'
          step-name: 'nginx-run'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-bucket: ${{ secrets.S3_LOGGING_BUCKET }}
          s3-path-prefix: 'github-actions/nginx-logs/'
